### ISSUE TITLE
Changed link

### ISSUE THREAD

**Issue by terdinatore** [hackmods/autoXOA#4]
Link has changed:
New Link is: https://github.com/kelektiv/node.bcrypt.js/archive/v1.0.2.tar.gz

![screenshot 2017-02-01 00 04 22](https://cloud.githubusercontent.com/assets/23297252/22488394/0d9b117c-e812-11e6-9baa-10cfd7c6b542.png)

**Comment by terdinatore** [comment]
Not related to the script

**Comment by hackmods** [comment]
Will adjust in script this week. Thanks for the feedback friend!
