### ISSUE TITLE
autoXOA.zxcv.us not resolvable 

### ISSUE THREAD

**Issue by DirkHeinke** [hackmods/autoXOA#9]
The link autoXOA.zxcv.us seems to be broken. 
```
autoxoa.zxcv.us’s server DNS address could not be found.

```

**Comment by TerrorFactor** [comment]
I made goo.gl/daqxrc that redirects to https://raw.githubusercontent.com/hackmods/autoXOA/master/autoinstall/AutoXOA.sh

Can be used as temporary fix.

**Comment by hackmods** [comment]
Sorry for the delay, I moved my dns to couldflare the other evening and one record was skipped, Thanks @TerrorFactor for temp work around! 👍
